Update StrideActivity.cs
stride3d/stride pull request #2351
Opened 2024-06-24 20:12 UTC by Rif009

# PR Details
🐞 Bug Fixes

- fix for android 14 see #2349

## Related Issue

https://github.com/stride3d/stride/issues/2349

## Types of changes
- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] **I have built and run the editor to try this change out.**

2024-06-24 21:48 UTC, Rif009 commented
> @Rif009 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

2024-06-24 22:08 UTC, MeharDT commented
Nice work! I think this is a useful workaround but it might be best to keep the PR open and eventually work in the updated Silk.NET binaries as they contain fixes for this and other Android bugs,

https://github.com/dotnet/Silk.NET/issues/2232

2024-06-24 23:35 UTC, Basewq commented
I suspect this might only require a `NotExported` flag rather than a `Exported` flag.
As per google's docs:
https://developer.android.com/develop/background-work/background-tasks/broadcasts#java

> If you flag your receiver with RECEIVER_NOT_EXPORTED, the receiver is able to receive some system broadcasts and broadcasts from your app, but not broadcasts from the highly privileged apps.

I think AudioManager does not fall under 'highly privileged apps', but will definitely test to see if this is the case.

2024-12-16 20:44 UTC, Basewq requested changes

2025-02-15 21:43 UTC, closed without merging