New Crowdin translations
stride3d/stride pull request #453
Opened 2019-05-19 08:45 UTC by xen2

Enjoy!

2019-05-19 09:26 UTC, Kryptos-FR requested changes
Looks like we lost quite a few Japanese translations that are still relevant.

2019-05-19 09:26 UTC, Kryptos-FR commented on sources/localization/ja/Xenko.GameStudio.ja.po
> -msgstr "プロジェクトに新規追加"
That translation is correct.

2019-05-19 09:26 UTC, Kryptos-FR commented on sources/localization/ja/Xenko.Core.Assets.Editor.ja.po
> -msgstr "エクスプローラーでエラーが起きました"
That translation might still be approximatively correct.

2019-05-19 09:26 UTC, Kryptos-FR commented on sources/localization/ja/Xenko.Core.Assets.Editor.ja.po
> -msgstr "現在のプロジェクトは変更を保存されていません。保存しますか？"
Translation is correct.

2019-05-19 09:26 UTC, Kryptos-FR commented on sources/localization/ja/Xenko.Core.Assets.Editor.ja.po
> -msgstr "パッケージをインポートしています"
Just replace パッケージ with プロジェクト

2019-05-19 09:26 UTC, Kryptos-FR commented on sources/localization/ja/Xenko.Core.Assets.Editor.ja.po
> -msgstr "パッケージのインポート中に例外が発生しました。"
Previous translation mostly correct.

2023-10-29 03:49 UTC, Eideren commented
Changing this to draft while merge conflicts and review haven't been taken care of

2026-07-16 22:11 UTC, closed without merging

2026-07-17 01:27 UTC, xen2 commented
👋 Apologies for the noise here.

This PR was closed unintentionally by a bad force-push to `master` on my side, which auto-closed a batch of PRs. GitHub won't let me (or you) reopen it, since the close is pinned to the now-rewritten commit.

I've contacted GitHub Support to try reopening these in bulk, but no guarantees. If this change is still relevant, it's a good opportunity to sync your branch with the latest master and open a fresh PR (your code is intact).

Sorry again for the disruption! 🙏